version: '3.3'
networks:
  tomcat:
    driver: bridge
services:
  tomcat:
    image: tomcat:9.0-jdk11-adoptopenjdk-hotspot
    ports:
      - 8080:8080
    volumes:
      - ../target/servlet-classloader-demo-1.0-SNAPSHOT.war:/usr/local/tomcat/webapps/classloader.war
    networks:
      - tomcat
