spring:
  application:
    name: spring-cloud-ribbon-demo
server:
  port: 8080
demo-server:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:9091,localhost:9092
    ServerListRefreshInterval: 15000
