spring:
  application:
    name: spring-cloud-gateway-demo
  cloud:
    gateway:
      routes:
      - id: host_route
        uri: http://127.0.0.1:9092
        predicates:
        - Path=/tmp
server:
  port: 8080
