version: '3.3'
networks:
  mysql:
    driver: bridge
services:
  server:
    image: mysql/mysql-server:8.0
    environment:
      - MYSQL_DATABASE=quartz_demo
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=demo
    ports:
      - 6603:3306
    command: ["--character-set-server=utf8", "--collation-server=utf8_general_ci"]
    networks:
      - mysql
  client:
    image: mysql/mysql-server:8.0
    entrypoint: /bin/bash
    stdin_open: true
    tty: true
    networks:
      - mysql
