version: '3.3'
networks:
  mysql:
    driver: bridge
services:
  mysql:
    image: mysql/mysql-server:8.0
    environment:
      - MYSQL_DATABASE=quartz_demo
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=demo
    ports:
      - 6603:3306
    command: ["--character-set-server=utf8", "--collation-server=utf8_general_ci"]
    volumes:
      - /tmp/spring-quartz-demo-mysql.general.log:/var/log/mysql.general.log
    networks:
      - mysql
  java01:
    image: openjdk:8-jdk-alpine
    volumes:
      - ../target/spring-quartz-demo-1.0-SNAPSHOT.jar:/app.jar
    entrypoint: java -Xms256m -Xmx512m -Djava.security.egd=file:/dev/./urandom -jar /app.jar
    depends_on:
      - mysql
    networks:
      - mysql
  java02:
    image: openjdk:8-jdk-alpine
    volumes:
      - ../target/spring-quartz-demo-1.0-SNAPSHOT.jar:/app.jar
    entrypoint: java -Xms256m -Xmx512m -Djava.security.egd=file:/dev/./urandom -jar /app.jar
    depends_on:
      - mysql
    networks:
      - mysql
